### ISSUE TITLE
remove my content

### ISSUE THREAD

**Issue by developer9998** [Duttbust/CapuchinMOTD#1]
i dont want my code being used for this product and i haven't wanted them in for a while now. remove them or i will resort to email and dmca.

**Comment by Duttbust** [comment]
i understand, i will have it remade, no longer using ur code. Give me a few
days/weeks to do so, i will promise it will be gone soon

**Comment by developer9998** [comment]
it has been over a month since this i left due to your neglect. remove my assets now.

**Comment by Duttbust** [comment]
you never gave me a reason, and jokerjosh said you don't have a cc on the code like fchb1239's code so you can't really do anything. But i will make it a promise that it will be removed soon, Do we have an agreement?

**Comment by developer9998** [comment]
i dont give a fuck about a reason, i want my assets gone by 8 PM EST

**Comment by Duttbust** [comment]
well im not at my moms right now so i dont have the files, so i really can't

**Comment by developer9998** [comment]
too bad sucks to be you

**Comment by Duttbust** [comment]
what do you want from me, im trying to reason with you and do what you want, i just need time

**Comment by developer9998** [comment]
its been over a month. ive given you plenty of time.

**Comment by Duttbust** [comment]
im sorry, jokerjosh told me that you can't really do anything, just give me a little bit more time and it will be gone i swear on my life

**Comment by developer9998** [comment]
well jokerjosh is a fucking bitch then for telling you that

**Comment by Duttbust** [comment]
i can see that, i just need more time and it will be gone, i swear

**Comment by Duttbust** [comment]
i have removed you're stuff, im now going to go back to working on what i was doing.

**Comment by PartyVR** [comment]
Thats Crazy
